### ISSUE TITLE
problem higlass-ingest

### ISSUE THREAD

**Issue by samuelCollombet** [higlass/higlass-manage#21]
Hi,
I have a problem setting up a new instance of Higlass. I installed higlass-manage in the following way:
```
$ conda create -p condaEnv/py3.6 python=3.6
$ source activate condaEnv/python.3.6
$ pip install higlass-manage
```
I can start Higlass:
`$ higlass-manage start -t ~/HiGlass/tmp -d ~/HiGlass/data -m ~/HiGlass/media -p 8181 --no-public-data -n test`
but then i do not manage to ingest any data:
```
$ higlass-manage ingest --hg-name test --filetype cooler --datatype matrix --assembly mm10  ~/HiGlass/data/SRP063320_NPC_WT_HiC_SRX1182728_G1.pairix.10kb.mcool
state True
name_text: 
hg_name: test
Traceback (most recent call last):
  File "/home/scollomb/programs/condaEnv/python.3.6/bin/higlass-manage", line 11, in <module>
    load_entry_point('higlass-manage==0.5.0', 'console_scripts', 'higlass-manage')()
  File "/home/scollomb/programs/condaEnv/python.3.6/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/scollomb/programs/condaEnv/python.3.6/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/scollomb/programs/condaEnv/python.3.6/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/scollomb/programs/condaEnv/python.3.6/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/scollomb/programs/condaEnv/python.3.6/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/scollomb/programs/condaEnv/python.3.6/lib/python3.6/site-packages/higlass_manage-0.5.0-py3.6.egg/higlass_manage.py", line 835, in ingest
  File "/home/scollomb/programs/condaEnv/python.3.6/lib/python3.6/site-packages/higlass_manage-0.5.0-py3.6.egg/higlass_manage.py", line 859, in _ingest
  File "/home/scollomb/programs/condaEnv/python.3.6/lib/python3.6/site-packages/higlass_manage-0.5.0-py3.6.egg/higlass_manage.py", line 170, in import_file
AttributeError: 'str' object has no attribute 'decode'
```
It works with the higlass docker so I guess I did something wrong somewhere... 
Many thanks,
Samuel

**Comment by pkerpedjiev** [comment]
Hi Samuel,

One of the dependencies was updated and now returns a string rather than bytes. I'll issue a new release later this evening or tomorrow.

In the meantime there's two things you can do:

1. Install slugid==1.0.7
2. Change line 170 of higlass_manage.py and remove the `.decode('utf8')` call.

Let me know if those don't work.

**Comment by samuelCollombet** [comment]
Dear Peter,
Yes it worked! Thanks! Let me know when you made the new release :)

**Comment by golobor** [comment]
Bump :)

**Comment by pkerpedjiev** [comment]
I really need to build that release. I refactored a ton of stuff in higlass-manage but haven't released it yet. This weekend I should have some time to get it out.

**Comment by GDSCSussex** [comment]
Hi,

I had the same issue as OP. I've taken your advice with the following:

1. Install slugid==1.0.7
2. Change line 170 of higlass_manage.py and remove the .decode('utf8') call.

I'm no longer getting the error message upon higlass-manage ingest. However, upon higlass-manage browse, i'm taken to an empty higlass browser. Any ideas?

```
wg45$ higlass-manage ingest /Users/wg45/Dropbox/Work/WD/higlass/2.mcool 
Inferred filetype: cooler
Inferred datatype: matrix
state True
Removing existing file in temporary dir: /tmp/higlass-docker/2.mcool
name_text: 
hg_name: default
command: python higlass-server/manage.py ingest_tileset --filename /tmp/2.mcool --filetype cooler --datatype matrix    --uid bhpaw0-LSZ-lMSLFL43yWA

```

Thanks!

Will

**Comment by pkerpedjiev** [comment]
@golobor I just issued a new release (v0.6.0), would you mind giving it a try when you get a chance?

@GDSCSussex Hi Will, it sounds like everything is working. `higlass-manage browse` should just open an empty browser. You can then add a track by clicking on the plus sign in the view header and searching for your dataset (`2.mcool`). A quicker way to do this is to use:

```
higlass-manage view /Users/wg45/Dropbox/Work/WD/higlass/2.mcool
```

**Comment by GDSCSussex** [comment]
@pkerpedjiev Oh dear, I see now! Thanks for your reply.
