### ISSUE TITLE
when I use local python to install higlass-manage ,I use the next command  "pip install higlass-manage" error.

### ISSUE THREAD

**Issue by hzaumsq** [higlass/higlass-manage#23]
Collecting pysam (from clodius>=0.10.3->higlass-manage)
  Using cached https://files.pythonhosted.org/packages/15/f6/ce0611aaa1865a616f7dc164fbf046eaf38f2b17c6d404403c56250beb93/pysam-0.15.2.tar.gz
    Complete output from command python setup.py egg_info:
    '.' 不是内部或外部命令，也不是可运行的程序
    或批处理文件。
    '.' 不是内部或外部命令，也不是可运行的程序
    或批处理文件。
    # pysam: no cython available - using pre-compiled C
    # pysam: htslib mode is shared
    # pysam: HTSLIB_CONFIGURE_OPTIONS=None
    # pysam: htslib configure options: None
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\msq\AppData\Local\Temp\pip-install-jc60ds7l\pysam\setup.py", line 223, in <module>
        htslib_make_options = run_make_print_config()
      File "C:\Users\msq\AppData\Local\Temp\pip-install-jc60ds7l\pysam\setup.py", line 69, in run_make_print_config
        stdout = subprocess.check_output(["make", "-s", "print-config"])
      File "d:\py3\lib\subprocess.py", line 395, in check_output
        **kwargs).stdout
      File "d:\py3\lib\subprocess.py", line 472, in run
        with Popen(*popenargs, **kwargs) as process:
      File "d:\py3\lib\subprocess.py", line 775, in __init__
        restore_signals, start_new_session)
      File "d:\py3\lib\subprocess.py", line 1178, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] 系统找不到指定的文件。

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\msq\AppData\Local\Temp\pip-install-jc60ds7l\pysa

**Comment by pkerpedjiev** [comment]
Look like you're using Windows. Unfortunately I don't have a windows environment available to help you debug. I'm really sorry.

There's two alternatives:

1. Use a linux virtual machine (e.g. using virtualbox)
2. Run the docker container directly. See here: https://github.com/higlass/higlass/wiki#running-locally
