### ISSUE TITLE
Install error - pybbi fails to build 

### ISSUE THREAD

**Issue by demmerle** [higlass/higlass-manage#26]
Running: OSX 10.12.6; Xcode 9.2; Xcode CLT 2347; Python 3.7.1; Conda 4.6.11; Docker Engine 18.09.2. 

Hi, thanks for making this. Excited to use it but I'm having an install problem. After calling `pip install higlass-manage` everything goes fine until....

`Running setup.py bdist_wheel for pysam ... done
  Stored in directory: /Users/demmerle/Library/Caches/pip/wheels/34/3b/bc/f3faaba907f333632357aae7bf09a453209a8c9c3cec4cddae
  Running setup.py bdist_wheel for pybbi ... error
  Complete output from command /anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/p_/xr0cxrx12msf6pb1xf0r07r40000gp/T/pip-install-74z1ht_7/pybbi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/p_/xr0cxrx12msf6pb1xf0r07r40000gp/T/pip-wheel-wum70wlg --python-tag cp37:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.7-x86_64-3.7
  creating build/lib.macosx-10.7-x86_64-3.7/bbi
  copying bbi/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/bbi
  running build_ext
  Compiling libkent...
  LIBRARY_PATH: /usr/local/opt/openssl/lib:
  C_INCLUDE_PATH: /anaconda3/include/libpng16:/anaconda3/include/openssl:/usr/local/opt/openssl/include:/usr/local/include/libpng16:
  cd src && /Applications/Xcode.app/Contents/Developer/usr/bin/make
  gcc -g -pthread -fPIC -static -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_GNU_SOURCE -DMACHTYPE_x86_64 -L/private/var/folders/p_/xr0cxrx12msf6pb1xf0r07r40000gp/T/pip-install-74z1ht_7/pybbi/src/x86_64 -L/usr/lib -lz -lc -lpthread -I/private/var/folders/p_/xr0cxrx12msf6pb1xf0r07r40000gp/T/pip-install-74z1ht_7/pybbi/include -I/private/var/folders/p_/xr0cxrx12msf6pb1xf0r07r40000gp/T/pip-install-74z1ht_7/pybbi/src -I/usr/include -o aliType.o -c aliType.c
  clang: warning: -lz: 'linker' input unused [-Wunused-command-line-argument]
  clang: warning: -lc: 'linker' input unused [-Wunused-command-line-argument]
  clang: warning: -lpthread: 'linker' input unused [-Wunused-command-line-argument]
  clang: warning: argument unused during compilation: '-L/private/var/folders/p_/xr0cxrx12msf6pb1xf0r07r40000gp/T/pip-install-74z1ht_7/pybbi/src/x86_64' [-Wunused-command-line-argument]
  clang: warning: argument unused during compilation: '-L/usr/lib' [-Wunused-command-line-argument]`

...at which point the gcc command runs repeatedly for maybe 100 iterations before installing the rest of the wheels, and then printing it's last error message 
` udc.c:39:10: fatal error: 'openssl/sha.h' file not found
    #include <openssl/sha.h>
             ^~~~~~~~~~~~~~~
    1 error generated.
    make[1]: *** [udc.o] Error 1
    make: *** [src/x86_64/libkent.a] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/p_/xr0cxrx12msf6pb1xf0r07r40000gp/T/pip-install-74z1ht_7/pybbi/setup.py", line 152, in <module>
        'build_ext': build_ext
      File "/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 143, in setup
        return distutils.core.setup(**attrs)
      File "/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/anaconda3/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/anaconda3/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/anaconda3/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/p_/xr0cxrx12msf6pb1xf0r07r40000gp/T/pip-install-74z1ht_7/pybbi/setup.py", line 86, in run
        check_call(['make', 'build-c'])
      File "/anaconda3/lib/python3.7/subprocess.py", line 341, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', 'build-c']' returned non-zero exit status 2.`

...and ends with this...
`Command "/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/p_/xr0cxrx12msf6pb1xf0r07r40000gp/T/pip-install-74z1ht_7/pybbi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/p_/xr0cxrx12msf6pb1xf0r07r40000gp/T/pip-record-mgajcosf/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/p_/xr0cxrx12msf6pb1xf0r07r40000gp/T/pip-install-74z1ht_7/pybbi/`

I tried pre-installing setuptools 0.40.9, but that didn't make a difference. I assume it's something silly in my mac environment, but I can't figure it out and was hoping you might have some thoughts. Thanks!

**Comment by pkerpedjiev** [comment]
Hey, sorry for the delay in answering. Any chance that the resolution to this issue helps? https://github.com/nvictus/pybbi/issues/2

**Comment by kalavattam** [comment]
Hi Peter and all,

I am helping a friend to install higlass-manage; we seem to be running into this error as well. While I also suspect it's something strange in the mac environment, I can't seem to pinpoint it.

For troubleshooting, I've attached the text printed to the terminal.

It's a system with macOS 10.14.4; we're attempting to set everything up in a conda environment via anaconda Python 3.7.

Looking into the [pybbi#2](https://github.com/nvictus/pybbi/issues/2) issue that you mention above, do you have any advice for adapting this approach to mac? For example (and forgive my ignorance), should I say, try installing these compilers and packages via something like homebrew?

[error_041619.txt](https://github.com/higlass/higlass-manage/files/3084102/error_041619.txt)

**Comment by kalavattam** [comment]
Hi Peter and all,

Just want to report that I encountered this error using a system with macOS 10.14.4; homebrew installation of libpng solved the issue.

Thanks!
Kris

**Comment by h-mori** [comment]
Yes,
```
brew install libpng
export C_INCLUDE_PATH="/usr/local/lib:/usr/local/include/libpng16:/usr/local/opt/openssl/include"
export LIBRARY_PATH="/usr/local/lib:/usr/local/include/libpng:/usr/local/opt/openssl/include"
pip install pybbi
pip install higlass-manage
```
solved the problem.
Thanks!
