### ISSUE TITLE
`higlass-manage view file.mcool` -> ModuleNotFoundError

### ISSUE THREAD

**Issue by mccalluc** [higlass/higlass-manage#38]
```
higlass-manage$ higlass-manage view ~/Downloads/4DNFI2A4OBS9.mcool 
Pulling latest image... 
done
Data directory: /Users/chuck/hg-data
Temp directory: ()
Starting... default 8989
Docker started: higlass-manage-container-default
sending request 1
Waiting to start (tilesets)...
sending request 2
Waiting to start (tilesets)...
sending request 3
Waiting to start (tilesets)...
sending request 4
Waiting to start (tilesets)...
sending request 5
Waiting to start (tilesets)...
sending request 6
Waiting to start (tilesets)...
sending request 7
Non 200 status code returned (502), waiting...
sending request 8
Non 200 status code returned (502), waiting...
sending request 9
Non 200 status code returned (502), waiting...
sending request 10
Non 200 status code returned (502), waiting...
sending request 11
Non 200 status code returned (502), waiting...
sending request 12
Non 200 status code returned (502), waiting...
sending request 13
Non 200 status code returned (502), waiting...
sending request 14
Non 200 status code returned (502), waiting...
sending request 15
public_data: True
Replaced js file
Started
Inferred filetype: cooler
Inferred datatype: matrix
state True
Inferred datatype: matrix
state True
state True
name_text: 
hg_name: default
command: python higlass-server/manage.py ingest_tileset --filename /tmp/4DNFI2A4OBS9.mcool --filetype cooler --datatype matrix    --uid YFkVEOCtR_6w8HCkpdyAMg
Traceback (most recent call last):
  File "/Users/chuck/anaconda3/envs/higlass-tutorial/bin/higlass-manage", line 10, in <module>
    sys.exit(cli())
  File "/Users/chuck/anaconda3/envs/higlass-tutorial/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/chuck/anaconda3/envs/higlass-tutorial/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/chuck/anaconda3/envs/higlass-tutorial/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/chuck/anaconda3/envs/higlass-tutorial/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/chuck/anaconda3/envs/higlass-tutorial/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/chuck/anaconda3/envs/higlass-tutorial/lib/python3.7/site-packages/higlass_manage/view.py", line 114, in view
    import higlass.client as hgc
ModuleNotFoundError: No module named 'higlass'
```

**Comment by pkerpedjiev** [comment]
See this PR: https://github.com/higlass/higlass-manage/pull/43

Should be able to update to the latest version of higlass-python once that is merged.
