### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by thomaslchan** [higlass/higlass-manage#39]
- Needed Fuse installed locally after pip install (https://osxfuse.github.io/)

- Installation:
  - Clean Conda environment with Python 3.6
  - $ pip install higlass-manage
  - $ pip install higlass-python (in requirements.txt, but does not install with above call?)

- "Quickly viewing a dataset"
  - $ wget https://s3.amazonaws.com/pkerp/public/hic-resolutions.cool
  - $ higlass-manage view hic-resolutions.cool
  - See below for error

<details>
<summary>Type Error</summary>
higlass-manage view hic-resolutions.cool
state True
temp_dir: /tmp/higlass-docker
Inferred filetype: cooler
Inferred datatype: matrix
Traceback (most recent call last):
  File "/anaconda3/envs/test/bin/higlass-manage", line 10, in <module>
    sys.exit(cli())
  File "/anaconda3/envs/test/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/anaconda3/envs/test/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/anaconda3/envs/test/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/anaconda3/envs/test/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/anaconda3/envs/test/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/anaconda3/envs/test/lib/python3.6/site-packages/higlass_manage/view.py", line 127, in view
    view = conf.add_view()
TypeError: add_view() missing 1 required positional argument: 'view'
</details>

**Comment by pkerpedjiev** [comment]
Uh oh, that must be a mismatch between version numbers. We updated the `higlass-python` API which contains the `add_view` call recently but must have forgotten to update higlass-manage to reflect that.

**Comment by pkerpedjiev** [comment]
Just submitted a PR to fix this: https://github.com/higlass/higlass-manage/pull/43.
