### ISSUE TITLE
test.sh does not run on MacOS

### ISSUE THREAD

**Issue by mccalluc** [higlass/higlass-manage#41]
`mktemp` is incompatible between linux and macos: Trying to run tests locally fails. Possible work-around on [stack-overflow](https://unix.stackexchange.com/questions/30091/fix-or-alternative-for-mktemp-in-os-x)

**Comment by scottkall** [comment]
Yep!

I was getting the following error in Mac OS 10.15.7 in a fresh conda env w/ python 3.9:

```
(higlass) ➜  higlass-manage git:(master) ./test.sh
mktemp: illegal option -- -
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 
```

so then I made the following change in `test.sh`:

```
# TMPDIR=$(mktemp --directory --tmpdir=${HOME})
TMPDIR=$(mktemp -d 2>/dev/null || mktemp -d -t 'mytmpdir') # trying workaround from https://unix.stackexchange.com/questions/30091/fix-or-alternative-for-mktemp-in-os-x
```

And things seemed to work until:

```
command: python higlass-server/manage.py ingest_tileset --filename /tmp/dixon.mcool --filetype cooler --datatype matrix    --uid V4ZVz8G-QmC1K3eSPTIOmg
Traceback (most recent call last):
  File "/Users/skallgren/opt/anaconda3/envs/higlass/bin/higlass-manage", line 8, in <module>
    sys.exit(cli())
  File "/Users/skallgren/opt/anaconda3/envs/higlass/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/skallgren/opt/anaconda3/envs/higlass/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/skallgren/opt/anaconda3/envs/higlass/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/skallgren/opt/anaconda3/envs/higlass/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/skallgren/opt/anaconda3/envs/higlass/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/skallgren/clones/higlass-manage/higlass_manage/view.py", line 157, in view
    from higlass.client import Track, View, ViewConf
ModuleNotFoundError: No module named 'higlass'
```

So I just gave up and switched to higlass-docker.

P.S. hi there @pkerpedjiev!
