### ISSUE TITLE
ingest mcool file error

### ISSUE THREAD

**Issue by biomystery** [higlass/higlass-manage#46]
cmd:

`higlass-manage ingest /tmp/higlass-docker/glucose_\
hi_30.mcool --project-name xxx`

errmsg 

```
state True
Inferred filetype: cooler
Inferred datatype: matrix
state True
state True
name_text:
hg_name: default
command: python higlass-server/manage.py ingest_tileset --filename /tmp/glucose_hi_30.mcool --filetype cooler --datatype matrix  --project-name "islet"  --uid SPC9uwo6RC6pkHmZKLs0qA
Traceback (most recent call last):
  File "/usr/local/bin/higlass-manage", line 11, in <module>
    load_entry_point('higlass-manage==0.7.3', 'console_scripts', 'higlass-manage')()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/higlass_manage/ingest.py", line 49, in ingest
    project_name
  File "/usr/local/lib/python3.6/site-packages/higlass_manage/ingest.py", line 80, in _ingest
    return import_file(hg_name, to_import, filetype, datatype, assembly, name, uid, no_upload, project_name)
  File "/usr/local/lib/python3.6/site-packages/higlass_manage/common.py", line 189, in import_file
    (exit_code, output) = container.exec_run(command)
ValueError: not enough values to unpack (expected 2, got 0)
```

**Comment by pkerpedjiev** [comment]
Oh, that's not good. Can you let me know what version your docker package is?

```
pip freeze | grep docker
```

**Comment by biomystery** [comment]
sure , thanks for looking into this!

```
$ pip freeze | grep docker
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after\
 that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.p\
ypa.io/en/latest/development/release-process/#python-2-support
```


```
$pip3 freeze | grep docker
docker==2.6.1
docker-compose==1.18.0
docker-pycreds==0.2.1
dockerpty==0.4.1
```

**Comment by pkerpedjiev** [comment]
I think your version of docker is out of date. Did you install `higlass-manage` using pip or clone the repo?

If the former, then could you try going into the directory and running `pip install -r requirements.txt`. If the latter `pip install --upgrade higlass-manage`?

**Comment by pkerpedjiev** [comment]
Oh, also you should switch to Python 3 if possible. We don't "officially" support Python 2.

**Comment by biomystery** [comment]
thanks, I will try your suggestions and close it if it is fixed. 

I was following the README

`pip install higlass-manage`

but failed. 

Then `(sudo) pip3  install higlass-manage` and manually install any dependency according to the prompt err msgs.

**Comment by biomystery** [comment]
great it works after `pip3 install --upgrade higlass-manage` 

thank you
