### ISSUE TITLE
higlass-manage browser

### ISSUE THREAD

**Issue by faryabib** [higlass/higlass-manage#60]
I'm trying to follow HiGlass documentation to locally setup HiGlass on a workstation with a static IP address, and use by desktop to view the data. On the workstation, "higlass-manage ingest" moves the test file sample.mcool to default directory /tmp/higlass-docker/sample.mcool. From my computer, I can load the HiGlass browser (Workstation_IP:8888/app), and view the list of public data sets, but not the local data sample.mcool.

Also following the higlass-manage usage fails as shown here.

> wget https://s3.amazonaws.com/pkerp/public/hic-resolutions.cool
> sudo higlass-manage view hic-resolutions.cool
state True
temp_dir: /tmp/higlass-docker
Inferred filetype: cooler
Inferred datatype: matrix
state True
Inferred datatype: matrix
state True
state True
name_text: 
hg_name: default
command: python higlass-server/manage.py ingest_tileset --filename /tmp/hic-resolutions.cool --filetype cooler --datatype matrix    --uid Bz-gWBMMR1SMa6uvx6h9HA
Traceback (most recent call last):
  File "/usr/local/bin/higlass-manage", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/higlass_manage/view.py", line 157, in view
    from higlass.client import Track, View, ViewConf
ModuleNotFoundError: No module named 'higlass'

**Comment by pkerpedjiev** [comment]
Hi! Could you try running?

```
pip install higlass-python
higlass-manage view hic-resolutions.cool
```

**Comment by faryabib** [comment]
Thanks. It worked. But, I thought the whole idea of having a container is to not install packages separately.

**Comment by bskubi** [comment]
I was having a similar issue:

> higlass-manage view demo.contact_matrix.cool 
> Pulling latest image... 
> done
> Data directory: /home/benjamin/hg-data
> Temp directory: ()
> Starting... default 8989
> Docker started: higlass-manage-container-default
> sending request 1
> Waiting to start (tilesets)...
> sending request 2
> Waiting to start (tilesets)...
> sending request 3
> Waiting to start (tilesets)...
> sending request 4
> Non 200 status code returned (502), waiting...
> sending request 5
> Non 200 status code returned (502), waiting...
> sending request 6
> Non 200 status code returned (502), waiting...
> sending request 7
> Non 200 status code returned (502), waiting...
> sending request 8
> Non 200 status code returned (502), waiting...
> sending request 9
> public_data: True
> Replaced js file
> Started
> Inferred filetype: cooler
> Inferred datatype: matrix
> state True
> Inferred datatype: matrix
> state True
> state True
> name_text: 
> hg_name: default
> command: python higlass-server/manage.py ingest_tileset --filename /tmp/demo.contact_matrix.cool --filetype cooler --datatype matrix    --uid dNmr82z4TOuMzOQYf7yGDQ
> Traceback (most recent call last):
>   File "/home/benjamin/anaconda3/bin/higlass-manage", line 8, in <module>
>     sys.exit(cli())
>              ^^^^^
>   File "/home/benjamin/anaconda3/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
>     return self.main(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/benjamin/anaconda3/lib/python3.11/site-packages/click/core.py", line 1078, in main
>     rv = self.invoke(ctx)
>          ^^^^^^^^^^^^^^^^
>   File "/home/benjamin/anaconda3/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/benjamin/anaconda3/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/benjamin/anaconda3/lib/python3.11/site-packages/click/core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/benjamin/anaconda3/lib/python3.11/site-packages/higlass_manage/view.py", line 157, in view
>     from higlass.client import Track, View, ViewConf
> ModuleNotFoundError: No module named 'higlass'


After running `pip install higlass-python` I tried viewing my .cool file again:


> higlass-manage view demo.contact_matrix.cool 
> state True
> temp_dir: /tmp/higlass-docker
> Inferred filetype: cooler
> Inferred datatype: matrix
> Traceback (most recent call last):
>   File "/home/benjamin/anaconda3/bin/higlass-manage", line 8, in <module>
>     sys.exit(cli())
>              ^^^^^
>   File "/home/benjamin/anaconda3/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
>     return self.main(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/benjamin/anaconda3/lib/python3.11/site-packages/click/core.py", line 1078, in main
>     rv = self.invoke(ctx)
>          ^^^^^^^^^^^^^^^^
>   File "/home/benjamin/anaconda3/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/benjamin/anaconda3/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/benjamin/anaconda3/lib/python3.11/site-packages/click/core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/benjamin/anaconda3/lib/python3.11/site-packages/higlass_manage/view.py", line 157, in view
>     from higlass.client import Track, View, ViewConf
> ModuleNotFoundError: No module named 'higlass.client'


Any idea where this error is coming from?

**Comment by Gon1976** [comment]
I have the same error after install higlass-python
higlass-manage view hic-resolutions.cool
state True
temp_dir: /tmp/higlass-docker
Inferred filetype: cooler
Inferred datatype: matrix
Traceback (most recent call last):
  File "/home/ggreif/miniconda3/envs/snakemake/bin/higlass-manage", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/ggreif/miniconda3/envs/snakemake/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ggreif/miniconda3/envs/snakemake/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/ggreif/miniconda3/envs/snakemake/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ggreif/miniconda3/envs/snakemake/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ggreif/miniconda3/envs/snakemake/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ggreif/miniconda3/envs/snakemake/lib/python3.12/site-packages/higlass_manage/view.py", line 157, in view
    from higlass.client import Track, View, ViewConf
ModuleNotFoundError: No module named 'higlass.client'

**Comment by Thepupa7** [comment]
I have the same problem `ModuleNotFoundError: No module named 'higlass.client'` when i use higlass-manage view .cool. Did you solve it?😭
