### ISSUE TITLE
Timeout Issues with Starting higlass-manage

### ISSUE THREAD

**Issue by arielpourmorady** [higlass/higlass-manage#62]
Hi there,

I am trying to using higlass-manage to view contact maps of my cooler files. I keep getting the following Timeout errors and I'm not entirely sure what to do to fix it. Any help would be really appreciated, thank you.

```
ariel@aphrodite:/$ higlass-manage start
Stopping previously running container
Pulling latest image... 
done
Data directory: /home/ariel/hg-data
Temp directory: ()
Starting... default 8989
Docker started: higlass-manage-container-default
sending request 1
Traceback (most recent call last):
  File "/home/ariel/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/ariel/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1356, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ariel/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/ariel/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/ariel/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/ariel/.local/lib/python3.6/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/home/ariel/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/ariel/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 428, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/ariel/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='gw-srv-01.rc.zi.columbia.edu', port=3128): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ariel/.local/lib/python3.6/site-packages/higlass_manage/start.py", line 368, in _start
    timeout=5,
  File "/home/ariel/.local/lib/python3.6/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/ariel/.local/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ariel/.local/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ariel/.local/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/ariel/.local/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='gw-srv-01.rc.zi.columbia.edu', port=3128): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ariel/.local/bin/higlass-manage", line 11, in <module>
    sys.exit(cli())
  File "/home/ariel/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ariel/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ariel/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ariel/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ariel/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ariel/.local/lib/python3.6/site-packages/higlass_manage/start.py", line 150, in start
    redis_port,
  File "/home/ariel/.local/lib/python3.6/site-packages/higlass_manage/start.py", line 384, in _start
    except requests.exceptions.ReadTimout:
AttributeError: module 'requests.exceptions' has no attribute 'ReadTimout'
```

**Comment by arielpourmorady** [comment]
I tried 

`higlass-manage start --site-url higlass.io
`
which I saw on the "Manage Higlass Instances" page and it produced the same errors. I am also somewhat new to coding, and this might have to do with the configuration of the server! I'm not entirely sure. Sorry for the trouble, and thanks for your help.

**Comment by pkerpedjiev** [comment]
You need to use the url of the server that you're running it on. Based on the log message maybe try this:

```
higlass-manage start --site-url gw-srv-01.rc.zi.columbia.edu
```
