### ISSUE TITLE
Symbol not found: ____chkstk_darwin

### ISSUE THREAD

**Issue by pkerpedjiev** [higlass/higlass-manage#63]
Here's the stack trace:

```
Traceback (most recent call last):
  File "/Users/pkerpedjiev/miniconda3/bin/higlass-manage", line 11, in <module>
    load_entry_point('higlass-manage', 'console_scripts', 'higlass-manage')()
  File "/Users/pkerpedjiev/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/pkerpedjiev/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/Users/pkerpedjiev/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/Users/pkerpedjiev/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/pkerpedjiev/projects/higlass-manage/higlass_manage/cli.py", line 3, in <module>
    from higlass_manage.ingest import ingest
  File "/Users/pkerpedjiev/projects/higlass-manage/higlass_manage/ingest.py", line 2, in <module>
    import clodius.cli.aggregate as cca
  File "/Users/pkerpedjiev/miniconda3/lib/python3.7/site-packages/clodius-0.15.2-py3.7.egg/clodius/cli/__init__.py", line 18, in <module>
  File "/Users/pkerpedjiev/miniconda3/lib/python3.7/site-packages/clodius-0.15.2-py3.7.egg/clodius/cli/aggregate.py", line 8, in <module>
  File "/Users/pkerpedjiev/miniconda3/lib/python3.7/site-packages/clodius-0.15.2-py3.7.egg/clodius/multivec.py", line 4, in <module>
  File "/Users/pkerpedjiev/miniconda3/lib/python3.7/site-packages/h5py-3.0.0rc1-py3.7-macosx-10.7-x86_64.egg/h5py/__init__.py", line 25, in <module>
    from . import _errors
ImportError: dlopen(/Users/pkerpedjiev/miniconda3/lib/python3.7/site-packages/h5py-3.0.0rc1-py3.7-macosx-10.7-x86_64.egg/h5py/_errors.cpython-37m-darwin.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /Users/pkerpedjiev/miniconda3/lib/python3.7/site-packages/h5py-3.0.0rc1-py3.7-macosx-10.7-x86_64.egg/h5py/.dylibs/libsz.2.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/pkerpedjiev/miniconda3/lib/python3.7/site-packages/h5py-3.0.0rc1-py3.7-macosx-10.7-x86_64.egg/h5py/.dylibs/libsz.2.dylib
```

**Comment by pkerpedjiev** [comment]
Fixed using `conda install h5py`
