### ISSUE TITLE
--OSError: [Errno 30] Read-only file system: '/host_mnt' -- Error in quickly viewing a dataset

### ISSUE THREAD

**Issue by kbq1453** [higlass/higlass-manage#66]
Hi ,

I followed tutorial in https://docs.higlass.io/tutorial.html  and  when I run "higlass-manage view /tmp/sample.mcool '' command , I always face same error : 
(OSError: [Errno 30] Read-only file system: '/host_mnt'   )

and all result of after run "higlass-manage view /tmp/sample.mcool '' command : 
Pulling latest image... 
done
Data directory: /Users/kbq5786/hg-data
Temp directory: ()
Starting... default 8989
Docker started: higlass-manage-container-default
sending request 1
Waiting to start (tilesets)...
sending request 2
Waiting to start (tilesets)...
sending request 3
Waiting to start (tilesets)...
sending request 4
Non 200 status code returned (502), waiting...
sending request 5
Non 200 status code returned (502), waiting...
sending request 6
Non 200 status code returned (502), waiting...
sending request 7
Non 200 status code returned (502), waiting...
sending request 8
Non 200 status code returned (502), waiting...
sending request 9
Non 200 status code returned (502), waiting...
sending request 10
Non 200 status code returned (502), waiting...
sending request 11
Non 200 status code returned (502), waiting...
sending request 12
public_data: True
Replaced js file
Started
Inferred filetype: cooler
Inferred datatype: matrix
state True
Inferred datatype: matrix
state True
state True
Traceback (most recent call last):
  File "/Users/kbq5786/opt/anaconda3/bin/higlass-manage", line 8, in <module>
    sys.exit(cli())
  File "/Users/kbq5786/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/kbq5786/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/kbq5786/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kbq5786/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/kbq5786/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/kbq5786/opt/anaconda3/lib/python3.8/site-packages/higlass_manage/view.py", line 144, in view
    uuid = _ingest(
  File "/Users/kbq5786/opt/anaconda3/lib/python3.8/site-packages/higlass_manage/ingest.py", line 122, in _ingest
    return import_file(
  File "/Users/kbq5786/opt/anaconda3/lib/python3.8/site-packages/higlass_manage/common.py", line 204, in import_file
    os.makedirs(temp_dir)
  File "/Users/kbq5786/opt/anaconda3/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/Users/kbq5786/opt/anaconda3/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/Users/kbq5786/opt/anaconda3/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/Users/kbq5786/opt/anaconda3/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/host_mnt'

What shoul I do? I check higlass-manage instances and firstly stop all instances then I try but again gave same error ?

**Comment by pkerpedjiev** [comment]
Hey, sorry about that. Docker changed some preferences. Fix is described here: https://github.com/higlass/higlass-manage/issues/64
