### ISSUE TITLE
requests / urllib3 error

### ISSUE THREAD

**Issue by liz-is** [higlass/higlass-manage#67]
Hello,

I'm having an error that was also mentioned in #65, and so is my colleague on a different OS version. 

Installing `higlass-manage` in a fresh python virtual env with Python 3.9 on MacOS Mojave gives the following error:

<details>
  <summary>Error traceback</summary>
  
```
(higlass-env) mpims-lingsim:~ lingsim$ higlass-manage start
Traceback (most recent call last):
  File "/Users/lingsim/higlass-env/lib/python3.9/site-packages/urllib3/response.py", line 572, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lingsim/higlass-env/lib/python3.9/site-packages/urllib3/response.py", line 331, in _error_catcher
    yield
  File "/Users/lingsim/higlass-env/lib/python3.9/site-packages/urllib3/response.py", line 637, in read_chunked
    self._update_chunk_length()
  File "/Users/lingsim/higlass-env/lib/python3.9/site-packages/urllib3/response.py", line 576, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lingsim/higlass-env/lib/python3.9/site-packages/requests/models.py", line 749, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/Users/lingsim/higlass-env/lib/python3.9/site-packages/urllib3/response.py", line 461, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/Users/lingsim/higlass-env/lib/python3.9/site-packages/urllib3/response.py", line 665, in read_chunked
    self._original_response.close()
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/lingsim/higlass-env/lib/python3.9/site-packages/urllib3/response.py", line 349, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lingsim/higlass-env/bin/higlass-manage", line 8, in <module>
    sys.exit(cli())
  File "/Users/lingsim/higlass-env/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/lingsim/higlass-env/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/lingsim/higlass-env/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/lingsim/higlass-env/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/lingsim/higlass-env/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/lingsim/higlass-env/lib/python3.9/site-packages/higlass_manage/start.py", line 134, in start
    _start(
  File "/Users/lingsim/higlass-env/lib/python3.9/site-packages/higlass_manage/start.py", line 180, in _start
    hg_container = client.containers.get(hg_container_name)
  File "/Users/lingsim/higlass-env/lib/python3.9/site-packages/docker/models/containers.py", line 889, in get
    resp = self.client.api.inspect_container(container_id)
  File "/Users/lingsim/higlass-env/lib/python3.9/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/Users/lingsim/higlass-env/lib/python3.9/site-packages/docker/api/container.py", line 774, in inspect_container
    self._get(self._url("/containers/{0}/json", container)), True
  File "/Users/lingsim/higlass-env/lib/python3.9/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/Users/lingsim/higlass-env/lib/python3.9/site-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/Users/lingsim/higlass-env/lib/python3.9/site-packages/requests/sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "/Users/lingsim/higlass-env/lib/python3.9/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/lingsim/higlass-env/lib/python3.9/site-packages/requests/sessions.py", line 662, in send
    r.content
  File "/Users/lingsim/higlass-env/lib/python3.9/site-packages/requests/models.py", line 827, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/Users/lingsim/higlass-env/lib/python3.9/site-packages/requests/models.py", line 752, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```
</details>

I was able to fix this by editing `response.py` as suggested here https://github.com/higlass/higlass-manage/issues/65#issuecomment-729329464 (well, I get a timeout error at the moment but as I mentioned in slack I suspect that a server needs restarting?)

My colleague had the same issue on MacOS Catalina and the same fix worked. But it's obviously not ideal to have to manually edit files inside installed packages! I'm not sure why this is happening now since this issue seems to have been around in urllib3 for a couple of years. Could you see again if you can reproduce this and if there's a more robust fix? Let me know if I can provide any more information to help reproduce or debug this. Thank you!

**Comment by pkerpedjiev** [comment]
You know what? I think there is a more robust fix. Next time it happens could you go to the application settings and clear the cookies for localhost:8989 or wherever you're running higlass?

![image](https://user-images.githubusercontent.com/2143629/100374732-b7ebec00-2fda-11eb-8e34-b3117adfa4b5.png)

**Comment by liz-is** [comment]
Hm, that does seem to fix it! I cleared the cookies and reinstalled urllib3 without the edit and don't get the same error.

Sorry, the person in the other issue seemed to have several problems and I thought that clearing the cache was the fix just for the blank webpage issue and I didn't realise they could be related. Thanks! I'll close this now.

**Comment by pkerpedjiev** [comment]
Tbh, I think the cache issue might have caused all the other problems and I didn't realize it until the end 😬

**Comment by liz-is** [comment]
I'll definitely try that first next time! 🙂
