### ISSUE TITLE
500 Server Error: Internal Server Error ("b'Mounts denied: EOF'")

### ISSUE THREAD

**Issue by xinyangbing** [higlass/higlass-manage#73]
Hi,
Any idea what could be causing this error? It started happening out of the blue today:

state False
HiGlass not running. Starting...
Stopping previously running container
Pulling latest image... doneData directory: /Users/xinyangbing/hg-data
Temp directory: /tmp/higlass-docker
Starting... default 8989
Traceback (most recent call last):
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/higlass_manage/ingest.py", line 66, in _ingest
    get_temp_dir(hg_name)
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/higlass_manage/common.py", line 198, in get_temp_dir
    raise HiGlassNotRunningException()
higlass_manage.common.HiGlassNotRunningException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/docker/api/client.py", line 259, in _raise_for_status
    response.raise_for_status()
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.41/containers/c75641576a15e33ed3b42f8ff195a7b92346334ede58fede22b38418a6358792/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyangbing/miniconda3/bin/higlass-manage", line 8, in <module>
    sys.exit(cli())
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/higlass_manage/ingest.py", line 40, in ingest
    _ingest(filename,
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/higlass_manage/ingest.py", line 69, in _ingest
    _start(hg_name=hg_name)
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/higlass_manage/start.py", line 135, in _start
    container = client.containers.run(image,
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/docker/models/containers.py", line 816, in run
    container.start()
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/docker/models/containers.py", line 404, in start
    return self.client.api.start(self.id, **kwargs)
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/docker/api/container.py", line 1108, in start
    self._raise_for_status(res)
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/docker/api/client.py", line 261, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'Mounts denied: EOF'")

**Comment by pkerpedjiev** [comment]
That looks like it's a Docker error. Have you tried googling "Mounts denied: EOF"?

You can verify that that's the case (or not) by running the docker commands directly:

```
docker pull higlass/higlass-docker # Ensure that you have the latest.
docker run --detach \
           --publish 8888:80 \
           --volume ~/hg-data:/data \
           --volume ~/hg-tmp:/tmp \
           --name higlass-container \
           higlass/higlass-docker
 ```
