### ISSUE TITLE
higlass-manage problem

### ISSUE THREAD

**Issue by fanghe0720** [higlass/higlass-manage#76]
Hi,
I'm a new user for higlass and the docker. I followed the tutorial https://docs.higlass.io/tutorial.html. I met the following problems in running the sample data. Could you help?

First, $**higlass-manage start** showed below. However no window is started in Firefox.
Pulling latest image... 
done
Data directory: /home/he/hg-data
Temp directory: ()
Starting... default 8989
Docker started: higlass-manage-container-default
sending request 1
Waiting to start (tilesets)...
sending request 2
Waiting to start (tilesets)...
sending request 3
Waiting to start (tilesets)...
sending request 4
Non 200 status code returned (502), waiting...
sending request 5
Non 200 status code returned (502), waiting...
sending request 6
Non 200 status code returned (502), waiting...
sending request 7
Non 200 status code returned (502), waiting...
sending request 8
Non 200 status code returned (502), waiting...
sending request 9
Non 200 status code returned (502), waiting...
sending request 10
public_data: True
Replaced js file
Started

Second, I tried to view the sample data by $**higlass-manage view sample.mcool** and it gave the error message as below.

state True
temp_dir: /tmp/higlass-docker
Inferred filetype: cooler
Inferred datatype: matrix
state True
Inferred datatype: matrix
state True
state True
Traceback (most recent call last):
  File "/home/condaEnv/py3.6/bin/higlass-manage", line 8, in <module>
    sys.exit(cli())
  File "/home/condaEnv/py3.6/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/condaEnv/py3.6/lib/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/condaEnv/py3.6/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/condaEnv/py3.6/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/condaEnv/py3.6/lib/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/condaEnv/py3.6/lib/python3.6/site-packages/higlass_manage/view.py", line 150, in view
    chromsizes_filename=chromsizes_filename,
  File "/home/condaEnv/py3.6/lib/python3.6/site-packages/higlass_manage/ingest.py", line 131, in _ingest
    project_name,
  File "/home/condaEnv/py3.6/lib/python3.6/site-packages/higlass_manage/common.py", line 216, in import_file
    os.link(filepath, to_import_path)
OSError: [Errno 18] Invalid cross-device link: '/home/HiGlass/data/sample.mcool' -> '/tmp/higlass-docker/sample.mcool'

**Comment by pkerpedjiev** [comment]
Hi there, could you post a link to the command you used to start higlass-manage? I think the issue is that you're on a network drive and Docker doesn't handle those very well.
