### ISSUE TITLE
Ingesting issue

### ISSUE THREAD

**Issue by ssmadha** [higlass/higlass-manage#8]
Hello, I'm trying to ingest a cool file for viewing in a browser. I'm able to run the ingest command as `sudo higlass-manage ingest Caco2Dif_1000000.1000.iced.cool` which runs without apparent error. When I go to the browser to try and view it however, it just shows a grey box with 'Loading...' indefinitely in the corner. When I check the logs, it does show an error traceback:
```
27/Sep/2018 18:17:02] ERROR [django.request:118] Internal Server Error: /api/v1/tileset_info/
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/opt/conda/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/conda/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/conda/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/opt/conda/lib/python3.6/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/conda/lib/python3.6/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "./tilesets/views.py", line 597, in tileset_info
    tut.get_datapath(tileset_object.datafile.url)
  File "/opt/conda/lib/python3.6/site-packages/hgtiles/cooler.py", line 511, in tileset_info
    (f, info) = make_mats(filepath)
  File "/opt/conda/lib/python3.6/site-packages/hgtiles/cooler.py", line 481, in make_mats
    info = get_info(filepath)
  File "/opt/conda/lib/python3.6/site-packages/hgtiles/cooler.py", line 169, in get_info
    logger.info('no zoom found')
NameError: name 'logger' is not defined
```

What really confuses me is that the folder "/opt/conda" doesn't even exist on my machine (conda stuff is installed elsewhere).

**Comment by pkerpedjiev** [comment]
Is your cooler file multi-res? If not, you can run `cooler zoomify Caco2Dif_1000000.1000.iced.cool` and ingest the resulting `mcool` file.

The error is thrown in the Docker container, which does have the `/opt/conda` directory.

**Comment by ssmadha** [comment]
Thanks, didn't realize I needed to do that. It does kinda work, but only gives me a white box where the heatmap should be. The scale goes up to 9e+6, which seems several orders of magnitude too high compared to some of the examples I looked at. Any idea why this may be?

**Comment by pkerpedjiev** [comment]
I guess you're looking at a small genome.

Try clicking on `Zoom to data extent` from the view options menu:

![image](https://user-images.githubusercontent.com/2143629/46173696-0378a300-c275-11e8-83bb-c2b94c73aa86.png)

**Comment by ssmadha** [comment]
That doesn't seem to do anything. I've tried manually zooming in and out as well. The scale does seem to disappear when I zoom in past a certain point, becoming just grey and having no scale except 0 at the bottom.

**Comment by pkerpedjiev** [comment]
Strange. Can you open the browser console and paste the output here?

**Comment by ssmadha** [comment]
Following is from after refreshing page, selecting to open up the mcool and zooming in and out a bit. The first TypeError: tileData is undefined is when I tried opening up the mcool.
```
 [Show/hide message details.] GET
http://localhost:8989/app/
[HTTP/1.1 304 Not Modified 0ms]
[Show/hide message details.] GET
http://localhost:8989/assets/styles/index.css
[HTTP/1.1 304 Not Modified 0ms]
[Show/hide message details.] GET
http://localhost:8989/assets/scripts-third-party/ga.js
[HTTP/1.1 304 Not Modified 0ms]
[Show/hide message details.] GET
https://unpkg.com/higlass@1.1.5/dist/scripts/hglib.js
[HTTP/2.0 200 OK 0ms]
[Show/hide message details.] GET
http://localhost:8989/assets/scripts/base.js
[HTTP/1.1 304 Not Modified 0ms]
[Show/hide message details.] GET
http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css
[HTTP/1.1 304 Not Modified 26ms]
[Show/hide message details.] GET
http://localhost:8989/assets/scripts/hg-launcher.js
[HTTP/1.1 304 Not Modified 0ms]
[Show/hide message details.] GET
https://unpkg.com/higlass@1.1.5/dist/styles/hglib.css
[HTTP/2.0 200 OK 0ms]
[Show/hide message details.] GET
https://cdnjs.cloudflare.com/ajax/libs/react/15.5.4/react.min.js
[HTTP/2.0 304 Not Modified 20ms]
[Show/hide message details.] GET
https://cdnjs.cloudflare.com/ajax/libs/react/15.5.4/react-dom.min.js
[HTTP/2.0 304 Not Modified 20ms]
[Show/hide message details.] GET
https://cdnjs.cloudflare.com/ajax/libs/pixi.js/4.5.2/pixi.min.js
[HTTP/2.0 304 Not Modified 20ms]
[Show/hide message details.] GET
https://cdnjs.cloudflare.com/ajax/libs/react-bootstrap/0.31.0/react-bootstrap.min.js
[HTTP/2.0 304 Not Modified 18ms]
[Show/hide message details.] GET
https://unpkg.com/higlass-multivec@0.1.10/dist/higlass-multivec.js
[HTTP/2.0 304 Not Modified 19ms]
[Show/hide message details.] GET
https://unpkg.com/higlass-time-interval-track@0.1.9/dist/higlass-time-interval-track.js
[HTTP/2.0 304 Not Modified 18ms]
[Show/hide message details.] GET
https://fonts.googleapis.com/css?family=Overpass:300,800
[HTTP/2.0 200 OK 97ms]
Pixi.js 4.5.2 - WebGL - http://www.pixijs.com/ index.js:245
Deprecated use of `createHgComponent`. The api is directly returned now. hglib.js:50965:5
[Show/hide message details.] GET
http://localhost:8989/assets/images/icons.svg
[HTTP/1.1 304 Not Modified 0ms]
[Show/hide message details.] XHRGET
http://localhost:8989/api/v1/viewconfs/?d=default
[HTTP/1.1 200 OK 4ms]
Loading failed for the <script> with source “http://www.google-analytics.com/analytics.js”. app:1
Source map error: request failed with status 404
Resource URL: https://unpkg.com/higlass@1.1.5/dist/scripts/hglib.js
Source Map URL: hglib.js.map[Learn More]
Error: WebGL warning: drawElements: This operation requires zeroing texture data. This is slow. SpriteRenderer.js:442:13
[Show/hide message details.] XHRGET
http://localhost:8989/api/v1/tilesets/?limit=10000&dt=matrix&dt=2d-projection&dt=arrowhead-domains&dt=2d-rectangle-domains&dt=2d-annotations&dt=bedpe&dt=chromsizes&dt=map-tiles&dt=image-tiles
[HTTP/1.1 200 OK 10ms]
[Show/hide message details.] XHRGET
http://higlass.io/api/v1/tilesets/?limit=10000&dt=matrix&dt=2d-projection&dt=arrowhead-domains&dt=2d-rectangle-domains&dt=2d-annotations&dt=bedpe&dt=chromsizes&dt=map-tiles&dt=image-tiles
[HTTP/1.1 200 OK 551ms]
[Show/hide message details.] XHRGET
http://localhost:8989/api/v1/tilesets/?limit=10000&dt=matrix&dt=2d-projection&dt=arrowhead-domains&dt=2d-rectangle-domains&dt=2d-annotations&dt=bedpe&dt=chromsizes&dt=map-tiles&dt=image-tiles
[HTTP/1.1 200 OK 11ms]
[Show/hide message details.] XHRGET
http://higlass.io/api/v1/tilesets/?limit=10000&dt=matrix&dt=2d-projection&dt=arrowhead-domains&dt=2d-rectangle-domains&dt=2d-annotations&dt=bedpe&dt=chromsizes&dt=map-tiles&dt=image-tiles
[HTTP/1.1 200 OK 563ms]
[Show/hide message details.] XHRGET
http://localhost:8989/api/v1/tileset_info/?d=HodfEqpDTP-BZybcJgatyw&s=bAJEtZ-yQeubPnMAcFZwTw
[HTTP/1.1 200 OK 4ms]
[Show/hide message details.] XHRGET
http://localhost:8989/api/v1/tiles/?d=HodfEqpDTP-BZybcJgatyw.3.0.2&d=HodfEqpDTP-BZybcJgatyw.3.0.3&d=HodfEqpDTP-BZybcJgatyw.3.1.2&d=HodfEqpDTP-BZybcJgatyw.3.1.3&d=HodfEqpDTP-BZybcJgatyw.3.2.2&d=HodfEqpDTP-BZybcJgatyw.3.2.3&d=HodfEqpDTP-BZybcJgatyw.3.3.3&d=HodfEqpDTP-BZybcJgatyw.3.2.4&d=HodfEqpDTP-BZybcJgatyw.3.3.4&d=HodfEqpDTP-BZybcJgatyw.3.2.5&d=HodfEqpDTP-BZybcJgatyw.3.3.5&d=HodfEqpDTP-BZybcJgatyw.3.2.6&d=HodfEqpDTP-BZybcJgatyw.3.3.6&s=bAJEtZ-yQeubPnMAcFZwTw
[HTTP/1.1 200 OK 207ms]
[Show/hide message details.] TypeError: tileData is undefined[Learn More]
hglib.js:15048:15
[Show/hide message details.] XHRGET
http://localhost:8989/api/v1/tiles/?d=HodfEqpDTP-BZybcJgatyw.3.0.1&d=HodfEqpDTP-BZybcJgatyw.3.0.4&d=HodfEqpDTP-BZybcJgatyw.3.1.1&d=HodfEqpDTP-BZybcJgatyw.3.1.4&d=HodfEqpDTP-BZybcJgatyw.3.1.2&d=HodfEqpDTP-BZybcJgatyw.3.2.4&d=HodfEqpDTP-BZybcJgatyw.3.1.3&d=HodfEqpDTP-BZybcJgatyw.3.3.4&d=HodfEqpDTP-BZybcJgatyw.3.4.4&d=HodfEqpDTP-BZybcJgatyw.3.1.5&d=HodfEqpDTP-BZybcJgatyw.3.4.5&d=HodfEqpDTP-BZybcJgatyw.3.1.6&d=HodfEqpDTP-BZybcJgatyw.3.4.6&s=bAJEtZ-yQeubPnMAcFZwTw
[HTTP/1.1 200 OK 327ms]
 [Show/hide message details.] XHRGET
http://localhost:8989/api/v1/tiles/?d=HodfEqpDTP-BZybcJgatyw.3.0.1&d=HodfEqpDTP-BZybcJgatyw.3.0.4&d=HodfEqpDTP-BZybcJgatyw.3.1.1&d=HodfEqpDTP-BZybcJgatyw.3.1.4&d=HodfEqpDTP-BZybcJgatyw.3.1.2&d=HodfEqpDTP-BZybcJgatyw.3.2.4&d=HodfEqpDTP-BZybcJgatyw.3.1.3&d=HodfEqpDTP-BZybcJgatyw.3.3.4&d=HodfEqpDTP-BZybcJgatyw.3.4.4&d=HodfEqpDTP-BZybcJgatyw.3.1.5&d=HodfEqpDTP-BZybcJgatyw.3.4.5&d=HodfEqpDTP-BZybcJgatyw.3.1.6&d=HodfEqpDTP-BZybcJgatyw.3.4.6&s=bAJEtZ-yQeubPnMAcFZwTw
[HTTP/1.1 200 OK 327ms]
[Show/hide message details.] TypeError: hoveredTiledPlot.listTracksAtPosition(...) is undefined[Learn More]
hglib.js:44128:48
[Show/hide message details.] TypeError: trackRenderer is null[Learn More] hglib.js:44824:23
[Show/hide message details.] TypeError: tileData is undefined[Learn More] hglib.js:15023:13
[Show/hide message details.] XHRGET
http://localhost:8989/api/v1/tiles/?d=HodfEqpDTP-BZybcJgatyw.3.0.0&d=HodfEqpDTP-BZybcJgatyw.3.0.5&d=HodfEqpDTP-BZybcJgatyw.3.0.1&d=HodfEqpDTP-BZybcJgatyw.3.1.5&d=HodfEqpDTP-BZybcJgatyw.3.0.2&d=HodfEqpDTP-BZybcJgatyw.3.2.5&d=HodfEqpDTP-BZybcJgatyw.3.0.3&d=HodfEqpDTP-BZybcJgatyw.3.3.5&d=HodfEqpDTP-BZybcJgatyw.3.0.4&d=HodfEqpDTP-BZybcJgatyw.3.4.5&d=HodfEqpDTP-BZybcJgatyw.3.5.5&d=HodfEqpDTP-BZybcJgatyw.3.0.6&d=HodfEqpDTP-BZybcJgatyw.3.5.6&d=HodfEqpDTP-BZybcJgatyw.3.0.7&d=HodfEqpDTP-BZybcJgatyw.3.1.7&d=HodfEqpDTP-BZybcJgatyw.3.2.7&d=HodfEqpDTP-BZybcJgatyw.3.3.7&d=HodfEqpDTP-BZybcJgatyw.3.4.7&d=HodfEqpDTP-BZybcJgatyw.3.5.7&s=bAJEtZ-yQeubPnMAcFZwTw
[HTTP/1.1 200 OK 358ms]
Unhandled promise rejection TypeError: "tileData is undefined"
higlass1.1.5/dist/scripts/hglib.js:15023:13higlass1.1.5/dist/scripts/hglib.js:15008:9higlass1.1.5/dist/scripts/hglib.js:14369:20higlass1.1.5/dist/scripts/hglib.js:15318:9higlass1.1.5/dist/scripts/hglib.js:21598:11higlass1.1.5/dist/scripts/hglib.js:94736:11higlass1.1.5/dist/scripts/hglib.js:94232:9higlass1.1.5/dist/scripts/hglib.js:93833:9updateComponenthttps://cdnjs.cloudflare.com/ajax/libs/react/15.5.4/react-dom.min.js:13:9206receiveComponenthttps://cdnjs.cloudflare.com/ajax/libs/react/15.5.4/react-dom.min.js:13:8605receiveComponenthttps://cdnjs.cloudflare.com/ajax/libs/react/15.5.4/react-dom.min.js:14:19233 hglib.js:51157:11
[Show/hide message details.] TypeError: tileData is undefined[Learn More] hglib.js:15023:13
[Show/hide message details.] XHRGET
http://localhost:8989/api/v1/tiles/?d=HodfEqpDTP-BZybcJgatyw.3.0.6&d=HodfEqpDTP-BZybcJgatyw.3.0.7&d=HodfEqpDTP-BZybcJgatyw.3.1.6&d=HodfEqpDTP-BZybcJgatyw.3.1.7&d=HodfEqpDTP-BZybcJgatyw.3.2.6&d=HodfEqpDTP-BZybcJgatyw.3.2.7&d=HodfEqpDTP-BZybcJgatyw.3.3.6&d=HodfEqpDTP-BZybcJgatyw.3.3.7&d=HodfEqpDTP-BZybcJgatyw.3.4.6&d=HodfEqpDTP-BZybcJgatyw.3.4.7&d=HodfEqpDTP-BZybcJgatyw.3.5.6&d=HodfEqpDTP-BZybcJgatyw.3.5.7&d=HodfEqpDTP-BZybcJgatyw.3.6.6&d=HodfEqpDTP-BZybcJgatyw.3.6.7&d=HodfEqpDTP-BZybcJgatyw.3.7.7&s=bAJEtZ-yQeubPnMAcFZwTw
[HTTP/1.1 200 OK 213ms]
[Show/hide message details.] TypeError: tileData is undefined[Learn More] hglib.js:15023:13
[Show/hide message details.] XHRGET
http://localhost:8989/api/v1/tiles/?d=HodfEqpDTP-BZybcJgatyw.2.0.0&d=HodfEqpDTP-BZybcJgatyw.2.0.1&d=HodfEqpDTP-BZybcJgatyw.2.0.2&d=HodfEqpDTP-BZybcJgatyw.2.0.3&d=HodfEqpDTP-BZybcJgatyw.2.1.1&d=HodfEqpDTP-BZybcJgatyw.2.1.2&d=HodfEqpDTP-BZybcJgatyw.2.1.3&d=HodfEqpDTP-BZybcJgatyw.2.2.2&d=HodfEqpDTP-BZybcJgatyw.2.2.3&d=HodfEqpDTP-BZybcJgatyw.2.3.3&s=bAJEtZ-yQeubPnMAcFZwTw
[HTTP/1.1 200 OK 160ms]
[Show/hide message details.] XHRGET
http://localhost:8989/api/v1/tiles/?d=HodfEqpDTP-BZybcJgatyw.3.0.0&d=HodfEqpDTP-BZybcJgatyw.3.0.1&d=HodfEqpDTP-BZybcJgatyw.3.0.2&d=HodfEqpDTP-BZybcJgatyw.3.0.3&d=HodfEqpDTP-BZybcJgatyw.3.0.4&d=HodfEqpDTP-BZybcJgatyw.3.0.5&d=HodfEqpDTP-BZybcJgatyw.3.0.6&d=HodfEqpDTP-BZybcJgatyw.3.0.7&d=HodfEqpDTP-BZybcJgatyw.3.1.1&d=HodfEqpDTP-BZybcJgatyw.3.1.2&d=HodfEqpDTP-BZybcJgatyw.3.1.3&d=HodfEqpDTP-BZybcJgatyw.3.1.4&d=HodfEqpDTP-BZybcJgatyw.3.1.5&d=HodfEqpDTP-BZybcJgatyw.3.1.6&d=HodfEqpDTP-BZybcJgatyw.3.1.7&d=HodfEqpDTP-BZybcJgatyw.3.2.2&d=HodfEqpDTP-BZybcJgatyw.3.2.3&d=HodfEqpDTP-BZybcJgatyw.3.2.4&d=HodfEqpDTP-BZybcJgatyw.3.2.5&d=HodfEqpDTP-BZybcJgatyw.3.2.6&s=bAJEtZ-yQeubPnMAcFZwTw
[HTTP/1.1 200 OK 205ms]
[Show/hide message details.] XHRGET
http://localhost:8989/api/v1/tiles/?d=HodfEqpDTP-BZybcJgatyw.3.2.7&d=HodfEqpDTP-BZybcJgatyw.3.3.3&d=HodfEqpDTP-BZybcJgatyw.3.3.4&d=HodfEqpDTP-BZybcJgatyw.3.3.5&d=HodfEqpDTP-BZybcJgatyw.3.3.6&d=HodfEqpDTP-BZybcJgatyw.3.3.7&d=HodfEqpDTP-BZybcJgatyw.3.4.4&d=HodfEqpDTP-BZybcJgatyw.3.4.5&d=HodfEqpDTP-BZybcJgatyw.3.4.6&d=HodfEqpDTP-BZybcJgatyw.3.4.7&d=HodfEqpDTP-BZybcJgatyw.3.5.5&d=HodfEqpDTP-BZybcJgatyw.3.5.6&d=HodfEqpDTP-BZybcJgatyw.3.5.7&d=HodfEqpDTP-BZybcJgatyw.3.6.6&d=HodfEqpDTP-BZybcJgatyw.3.6.7&d=HodfEqpDTP-BZybcJgatyw.3.7.7&s=bAJEtZ-yQeubPnMAcFZwTw
[HTTP/1.1 200 OK 316ms]
```

**Comment by pkerpedjiev** [comment]
Could you share the cooler file you're using so that I can try it out locally? If it's not public, you're welcome to email it to me privately.

**Comment by ssmadha** [comment]
Sure, it's not public data, so I should probably just email it. Where should I send it?

**Comment by pkerpedjiev** [comment]
pkerpedjiev@gmail.com

**Comment by flekschas** [comment]
@ssmadha Are you all set or this still an issue?

**Comment by ssmadha** [comment]
Oh, yeah, sorry, this is done, was my dumb mistake.
