### ISSUE TITLE
ingest error, file not found in /tmp/ dir

### ISSUE THREAD

**Issue by mutedHjia** [higlass/higlass-manage#80]
Hi, i was trying to ingest some files but it keeps returning error FileNotFoundError: [Errno 2] No such file or directory: /tmp/<filenames> . I tried to reinstall higlass-manage it still doesn’t work. Anyone know how to fix it? Thank you!

`higlass-manage ingest --filetype multivec \
>     --datatype multivec allChr.multires.mv5 \
>     --project-name 000_epimap833
state True
state True
state True
Removing existing file in temporary dir: /tmp/higlass-docker/allChr.multires.mv5
name_text: 
hg_name: default
command: python higlass-server/manage.py ingest_tileset --filename /tmp/allChr.multires.mv5 --filetype multivec --datatype multivec  --project-name "000_epimap833"  --uid O8HB_1_tTFWawgYFJ1vEyw
ERROR: Traceback (most recent call last):
  File "higlass-server/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/higlass/projects/higlass-server/tilesets/management/commands/ingest_tileset.py", line 236, in handle
    ingest(**options)
  File "/home/higlass/projects/higlass-server/tilesets/management/commands/ingest_tileset.py", line 80, in ingest
    django_file = File(open(filename,'rb'))
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/allChr.multires.mv5'`

**Comment by pkerpedjiev** [comment]
What operating system are you on?

Is `/tmp` a network drive by chance?

**Comment by mutedHjia** [comment]
Thank you. I am using Amazon EC2 instance Linux. 

Actually, after I restart higlass server, i can ingest it properly.

**Comment by corinsexton** [comment]
I'm running into this same error. Unable to ingest data because 

```FileNotFoundError: [Errno 2] No such file or directory: '/tmp/hff.mcool'```

The file copies just fine to `/tmp/higlass-docker/hff.mcool`. Any ideas?

**Comment by corinsexton** [comment]
Turns out it was an issue with Rancher Desktop. The container couldn't see the mounted volumes. I'm working on an M2 MacBook. When I switched to Docker Desktop it had no problem ingesting.
