### ISSUE TITLE
error at higlass-manage installation with pip

### ISSUE THREAD

**Issue by mrbertp** [higlass/higlass-manage#87]
Hello, I have tried to install higlass-manage with pip:

`$ C:\Users\Bert\Desktop\AFA25_166_micro-C>pip install higlass-manage`

and this error showed up:

>Defaulting to user installation because normal site-packages is not writeable
Collecting higlass-manage
  Using cached higlass-manage-0.8.0.tar.gz (15 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting Click (from higlass-manage)
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting clodius>=0.10.3 (from higlass-manage)
  Using cached clodius-0.20.1-py2.py3-none-any.whl (82 kB)
Collecting cooler>=0.8.0 (from higlass-manage)
  Using cached cooler-0.9.1-py2.py3-none-any.whl (103 kB)
Collecting pandas>=0.19 (from higlass-manage)
  Using cached pandas-2.0.1-cp310-cp310-win_amd64.whl (10.7 MB)
Collecting docker (from higlass-manage)
  Using cached docker-6.1.2-py3-none-any.whl (148 kB)
Collecting requests (from higlass-manage)
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting dask (from clodius>=0.10.3->higlass-manage)
  Using cached dask-2023.5.0-py3-none-any.whl (1.2 MB)
Collecting h5py (from clodius>=0.10.3->higlass-manage)
  Using cached h5py-3.8.0-cp310-cp310-win_amd64.whl (2.6 MB)
Collecting negspy (from clodius>=0.10.3->higlass-manage)
  Using cached negspy-0.2.24.tar.gz (1.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in c:\program files\python310\lib\site-packages (from clodius>=0.10.3->higlass-manage) (1.23.1)
Collecting pybbi>=0.2.0 (from clodius>=0.10.3->higlass-manage)
  Using cached pybbi-0.3.4.tar.gz (34.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
>  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Bert\AppData\Roaming\Python\Python310\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Bert\AppData\Roaming\Python\Python310\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Bert\AppData\Roaming\Python\Python310\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Bert\AppData\Local\Temp\pip-build-env-4dpw0qj9\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\Bert\AppData\Local\Temp\pip-build-env-4dpw0qj9\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\Bert\AppData\Local\Temp\pip-build-env-4dpw0qj9\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 11, in <module>
      AttributeError: module 'os' has no attribute 'uname'. Did you mean: 'name'?
      [end of output]

 > note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

> × Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

> note: This error originates from a subprocess, and is likely not a problem with pip.

Do I lack something in my environment or is it a version problem or...?

Thank you very much.

**Comment by smitkadvani** [comment]
I'm facing same problem.

**Comment by pkerpedjiev** [comment]
@smitkadvani are you also on Windows?

**Comment by smitkadvani** [comment]
I'm on macM2

**Comment by nyuhic** [comment]
Facing the same issue. On windows.

**Comment by bskubi** [comment]
Same issue on Windows. The problem generating this specific error is that one of higlass-manage's dependencies, pybbi, relies on the os.uname method which is only available on certain flavors of linux. This issue still results when I try to install pybbi either independently via pip or when I try to build it from source.

**Comment by jouvrard05** [comment]
Hi, 

I am facing the same problem on Windows, @bskubi did you manage to solve the problem ? Thank you

**Comment by bskubi** [comment]
@jouvrard05 I didn't, unfortunately. I can use HiGlass on my linux desktop and static images can be created using the cooltools library so that's what I'm resorting to for now.

**Comment by bskubi** [comment]
@jouvrard05 I tried a few things (dockerizing higlass-manage, using WSL) but the only thing that worked was straight-up dual booting linux (Ubuntu) and running higlass-manage that way. Fortunately it works just fine that way and I'd been meaning to anyway!

Note that whatever pip pulls down when you run `pip install higlass-manage` appears to be out of date. `pip install git+https://github.com/higlass/higlass-manage.git` worked smoothly for me.

I also had to do a few additional steps not described in the installation instructions:

0. Install Docker
1. Add `export PATH="$HOME/.local/bin:$PATH"` to the end of ~/.bashrc and run `source ~/.bashrc`.
2. `sudo usermod -aG docker $USER`
3. `newgrp docker`
