### ISSUE TITLE
higlass file not found in /tmp error

### ISSUE THREAD

**Issue by pmanninghall** [higlass/higlass-manage#91]
Hello,
I am running ubuntu on a virtual machine situated in my windows comp.

I have installed Higlass-manage and docker.  I can get the local blank higlass window using higlass-manage start and navigating to the local host on firefox.

However, when i try to add data using "ingest" or "view" I get this message.  Note that when i navigate to /tmp "sample.mcool" is in the directory.  The same sort of message also happens when I tried to load other data.

$ higlass-manage ingest /tmp/sample.mcool

state True
Inferred filetype: cooler
Inferred datatype: matrix
state True
state True
Removing existing file in temporary dir: /tmp/higlass-docker/sample.mcool
name_text: 
hg_name: default
command: python higlass-server/manage.py ingest_tileset --filename /tmp/sample.mcool --filetype cooler --datatype matrix    --uid Frx4RvSxQAyaa-cnvuZjeA
ERROR: Traceback (most recent call last):
  File "higlass-server/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/higlass/projects/higlass-server/tilesets/management/commands/ingest_tileset.py", line 236, in handle
    ingest(**options)
  File "/home/higlass/projects/higlass-server/tilesets/management/commands/ingest_tileset.py", line 80, in ingest
    django_file = File(open(filename,'rb'))
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/sample.mcool'

**Comment by Roleren** [comment]
Same here; the tutorial is now incorrect (I'm on Ubuntu 24).
