### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by alexandremarcil** [higlass/higlass-manage#95]
Hi, 
trying to install on a Mac M1 (MacOS 14.2.1). Getting this error:

pip install higlass-manage
Collecting higlass-manage
  Using cached higlass-manage-0.8.0.tar.gz (15 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: Click in /Users/alex/miniconda3/envs/cool/lib/python3.12/site-packages (from higlass-manage) (8.1.7)
Collecting clodius>=0.10.3 (from higlass-manage)
  Using cached clodius-0.20.1-py2.py3-none-any.whl.metadata (3.1 kB)
Requirement already satisfied: cooler>=0.8.0 in /Users/alex/miniconda3/envs/cool/lib/python3.12/site-packages (from higlass-manage) (0.9.3)
Requirement already satisfied: pandas>=0.19 in /Users/alex/miniconda3/envs/cool/lib/python3.12/site-packages (from higlass-manage) (2.1.4)
Collecting docker (from higlass-manage)
  Using cached docker-7.0.0-py3-none-any.whl.metadata (3.5 kB)
Collecting requests (from higlass-manage)
  Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting dask (from clodius>=0.10.3->higlass-manage)
  Using cached dask-2024.1.1-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: h5py in /Users/alex/miniconda3/envs/cool/lib/python3.12/site-packages (from clodius>=0.10.3->higlass-manage) (3.9.0)
Collecting negspy (from clodius>=0.10.3->higlass-manage)
  Using cached negspy-0.2.24.tar.gz (1.7 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /Users/alex/miniconda3/envs/cool/lib/python3.12/site-packages (from clodius>=0.10.3->higlass-manage) (1.26.3)
Collecting pybbi>=0.2.0 (from clodius>=0.10.3->higlass-manage)
  Using cached pybbi-0.3.6.tar.gz (34.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [43 lines of output]
      Traceback (most recent call last):
        File "/private/var/folders/nq/pc_24wgn6rx_r39nc6ddm5880000gn/T/pip-build-env-yakzojkd/overlay/lib/python3.12/site-packages/pkgconfig/pkgconfig.py", line 91, in _wrapper
          return func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/nq/pc_24wgn6rx_r39nc6ddm5880000gn/T/pip-build-env-yakzojkd/overlay/lib/python3.12/site-packages/pkgconfig/pkgconfig.py", line 125, in exists
          return call(cmd) == 0
                 ^^^^^^^^^
        File "/Users/alex/miniconda3/envs/cool/lib/python3.12/subprocess.py", line 389, in call
          with Popen(*popenargs, **kwargs) as p:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/alex/miniconda3/envs/cool/lib/python3.12/subprocess.py", line 1026, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/Users/alex/miniconda3/envs/cool/lib/python3.12/subprocess.py", line 1950, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'pkg-config'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/Users/alex/miniconda3/envs/cool/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/alex/miniconda3/envs/cool/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/alex/miniconda3/envs/cool/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/nq/pc_24wgn6rx_r39nc6ddm5880000gn/T/pip-build-env-yakzojkd/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/nq/pc_24wgn6rx_r39nc6ddm5880000gn/T/pip-build-env-yakzojkd/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/nq/pc_24wgn6rx_r39nc6ddm5880000gn/T/pip-build-env-yakzojkd/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 49, in <module>
        File "/private/var/folders/nq/pc_24wgn6rx_r39nc6ddm5880000gn/T/pip-build-env-yakzojkd/overlay/lib/python3.12/site-packages/pkgconfig/pkgconfig.py", line 248, in parse
          _raise_if_not_exists(package)
        File "/private/var/folders/nq/pc_24wgn6rx_r39nc6ddm5880000gn/T/pip-build-env-yakzojkd/overlay/lib/python3.12/site-packages/pkgconfig/pkgconfig.py", line 102, in _raise_if_not_exists
          if not exists(package):
                 ^^^^^^^^^^^^^^^
        File "/private/var/folders/nq/pc_24wgn6rx_r39nc6ddm5880000gn/T/pip-build-env-yakzojkd/overlay/lib/python3.12/site-packages/pkgconfig/pkgconfig.py", line 93, in _wrapper
          raise EnvironmentError("pkg-config probably not installed: %r" % e)
      OSError: pkg-config probably not installed: FileNotFoundError(2, 'No such file or directory')
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

Help please!

**Comment by pkerpedjiev** [comment]
Sorry for the late reply but just to cover our bases, did you try the solution suggested here?

https://stackoverflow.com/a/53588495
