### ISSUE TITLE
Ingesting a gene annotation .bed file, Error: No such file or directory: '/tmp/geneAnnotationsExonUnionsMM39.bed.beddb'

### ISSUE THREAD

**Issue by narzouni** [higlass/higlass-manage#97]
Hello,

I have a question about an issue using `higlass-manage`.  I hope I receive some feedback.

I am trying to ingest a gene annotation .bed file, so I can see the gene labels on higlass visualization of .mcool files.

I created the file `geneAnnotationsExonUnionsMM39.bed` file based on the following link:

https://docs.higlass.io/data_preparation.html#gene-annotation-tracks

I am trying to ingest the file using the following command:

      higlass-manage ingest geneAnnotationsExonUnionsMM39.bed --filetype bedfile --datatype bedlike  --assembly mm39 

I also tried using `--datatype gene-annotation`, but both gave me the error below.

It gives the following error:

command: python higlass-server/manage.py ingest_tileset --filename /tmp/geneAnnotationsMM39.bed.beddb --filetype beddb --datatype bedlike  --project-name "PenaLabHiCData" --coordSystem mm39 --uid A_hYkLnSTDqVIRkl6ELaiQ
ERROR: Traceback (most recent call last):
  File "higlass-server/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/higlass/projects/higlass-server/tilesets/management/commands/ingest_tileset.py", line 236, in handle
    ingest(**options)
  File "/home/higlass/projects/higlass-server/tilesets/management/commands/ingest_tileset.py", line 80, in ingest
    django_file = File(open(filename,'rb'))
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/geneAnnotationsMM39.bed.beddb'

**Comment by pkerpedjiev** [comment]
Is there any other output before that?

`higlass-manage` should have tried to aggregate your bedfile and then ingest it:

https://github.com/higlass/higlass-manage/blob/master/higlass_manage/ingest.py#L154

**Comment by narzouni** [comment]
I looked at the higlass-manage code before, and I realized it will aggregate the bed file to create the .beddb, but it was still giving the above errors. I think I was able to find the issue. It was in the chromsizes file. however, I was expecting to see the gene names displayed. Is there any way to do that? when I created the file `geneAnnotationsExonUnionsMM39.bed`, I followed the link in my initial message. However, if I hover over the notation, I can see the names displayed. I was just hoping that it will display the name without hovering because I saw that in some `higlass` docs. Thank you so much.

**Comment by narzouni** [comment]
![export](https://github.com/higlass/higlass-manage/assets/74695095/3b718770-2177-4c33-8d95-6e45048a3a13)

**Comment by narzouni** [comment]
> ![export](https://private-user-images.githubusercontent.com/74695095/336915664-3b718770-2177-4c33-8d95-6e45048a3a13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MDMyODEsIm5iZiI6MTcxNzYwMjk4MSwicGF0aCI6Ii83NDY5NTA5NS8zMzY5MTU2NjQtM2I3MTg3NzAtMjE3Ny00YzMzLThkOTUtNmU0NTA0OGEzYTEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDE1NTYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MjczMTRiZmYyMDNiNTE4ODM0ZWI5NTcwMGYwMDljNjU0MmQ1NTUwYWI1NjE5YTUxMDJkYjQ0NGQ4YjQyNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YTayBue7-SmCwko2xDVZHqSpJkE4HLQZem92B5kybhg)

I was expecting to see the names of the genes, but I get the above attached image. It is good enough if there is no solution because if I hover over it, I can see the information.
